title: A coding column.
description: >-
  My personal take on coding, software design and programming languages.
baseurl: ""
url: ""
#twitter_username: NetzwergX
github_username:  NetzwergX

collections:
  category:
    output: true
  portfolio:
    output: true


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Sebastian Teumert
      show_license: true
      permalink: /blog/:title-:year
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
      permalink: /blog/:title/
  -
    scope:
      path: ""
      type: portfolio
    values:
      layout: "default"
      permalink: /portfolio/:title/

show_excerpts: true

header_pages:
#  - portfolio.html
  - cv.html
  - about.md
minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
