title: A coding column.
email: sebastian.teumert@gmx.de
description: >- 
  My personal take on coding, software design and programming languages.
baseurl: "" 
url: "" 
twitter_username: NetzwergX
github_username:  NetzwergX

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Sebastian Teumert
      show_license: true
      permalink: /blog/:title-:year

show_excerpts: true

header_pages:
  - archive.html
  - categories.html
  - about.md
minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

