permalink: /:categories/:year-:month-:day-:title.html
url: /
exclude: [README.md]
timezone: Europe/Berlin
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "underline", "highlight"]
  
author: 
  name: "Sebastian Teumert"
  href: "/index.html"
  email: "sebastian.teumert@gmx.de"

lang:
  default: de
  de:
    lang: "Deutsch"
    title: "Sebastian Teumert"
    nav:			
      start: "Start"
      about: "Über mich"
      software: "Software"
      blog: "Artikel"   
    blog:
      year: "Artikel"
    article:
      by: 'verfasst von'
      time: 'am'
  en:
    lang: "English"
    title: "Sebastian Teumert"
    nav: 			
      start: "Home"
      about: "About me"
      software: "Software"
      blog: "Articles"  
    blog:
      year: "Articles"
    article:
      by: 'written by'
      time: 'on'
